service:
  name: ${self:custom.NAME}

plugins:
  - serverless-domain-manager
  - serverless-s3-sync

frameworkVersion: ">=1.27.0"

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  stage: ${self:custom.STAGE}

custom:
  NAME: pastory-web
  STAGE: ${file(./configs/env.js):exporter.STAGE}
  BASE_URL: ${file(./configs/env.js):exporter.BASE_URL}
  ENDPOINT_ENV: ${file(./configs/env.js):exporter.ENDPOINT_ENV}
  NODE_ENV: ${file(./configs/env.js):exporter.NODE_ENV}
  customDomain:
    domainName: pastory.me
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  s3Sync:
    - bucketName: pastory-static-assets
      bucketPrefix: _nuxt
      localDir: .nuxt/dist/client
    - bucketName: pastory-static-assets
      bucketPrefix: static
      localDir: app/static

# 少しでもデプロイのパッケージファイルを少なくする
package:
  excludeDevDependencies: true
  exclude:
    - .**
    - .**/*
    - app/**
    - LICENSE
    - README.md
    - package.json
    - yarn.lock
    # Node.js 上で使われないモジュール
    # 重いものを優先的に除外
    - node_modules/babel**/**
    - node_modules/caniuse-db/**
    - node_modules/prettier/**
    - node_modules/yargs/**
    - node_modules/xxhashjs/**
    - node_modules/jschardet/**
    - node_modules/**/*.md
    - node_modules/**/bin/**
  include:
    - server/**
    - configs/**
    - nuxt.config.js
    - .nuxt/**
    - node_modules/autoprefixer/**
    - node_modules/babel-runtime/**
    - node_modules/babel-extract-comments/**

functions:
  handler:
    handler: server/handler.handler
    timeout: 30
    memorySize: 128
    environment:
      BASE_URL: ${self:custom.BASE_URL}
      ENDPOINT_ENV: ${self:custom.ENDPOINT_ENV}
      NODE_ENV: ${self:custom.NODE_ENV}
    events:
      - http:
          path: '/'
          method: get
      - http:
          path: '{proxy+}'
          method: get

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: pastory-static-assets
        AccessControl: PublicRead
    AssetsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: AssetsBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement: [
            {
              Action: ['s3:GetObject'],
              Effect: 'Allow',
              Resource: {
                Fn::Join: ['', ['arn:aws:s3:::', { Ref: 'AssetsBucket' }, '/*']],
              },
              Principal: '*'
            },
          ]
